// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkPilot.Infrastructure.Persistence;

#nullable disable

namespace WorkPilot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WorkPilotDbContext))]
    partial class WorkPilotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkPilot.Domain.Modules.Agent.AgentRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("WorkflowInstanceId")
                        .IsUnique();

                    b.ToTable("agent_runs", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Agent.AgentStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("ArgumentsJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<string>("ReasoningUrl")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("AgentRunId", "Ordinal")
                        .IsUnique();

                    b.ToTable("agent_steps", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Agent.ToolCall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentStepId")
                        .HasColumnType("uuid");

                    b.Property<string>("InputPayloadUrl")
                        .HasColumnType("text");

                    b.Property<string>("OutputPayloadUrl")
                        .HasColumnType("text");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AgentStepId");

                    b.ToTable("tool_calls", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Agent.WorkflowEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.ToTable("workflow_events", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Agent.WorkflowInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DefinitionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("workflow_instances", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Agent.WorkflowStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadUrl")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowInstanceId");

                    b.ToTable("workflow_steps", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Applications.ApplicationAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("JobApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JobApplicationId");

                    b.ToTable("application_answers", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Applications.ApplicationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("JobApplicationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("JobApplicationId");

                    b.ToTable("application_events", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Applications.JobApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CoverLetterVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResumeVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("job_applications", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Approvals.Approval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DecidedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("EvidenceJson")
                        .HasColumnType("jsonb");

                    b.Property<bool>("ExplicitlyConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("RiskTier")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "RequestedAt");

                    b.HasIndex("TargetType", "TargetId");

                    b.ToTable("approvals", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.ToTable("audit_logs", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Calendar.CalendarEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalCalendarId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.ToTable("calendar_events", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Integrations.Integration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("integrations", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Integrations.OAuthConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("oauth_connections", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Jobs.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DedupKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("DedupRuleVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PostedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PrimaryLinkId")
                        .HasColumnType("uuid");

                    b.Property<string>("RemoteType")
                        .HasColumnType("text");

                    b.Property<decimal?>("SalaryRangeMax")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SalaryRangeMin")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("DedupKey");

                    b.ToTable("jobs", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Jobs.JobMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("MatchedSkills")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RankedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "ProfileId")
                        .IsUnique();

                    b.ToTable("job_matches", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Jobs.JobSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JobSourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("JobId");

                    b.HasIndex("JobSourceId", "ExternalId");

                    b.ToTable("job_snapshots", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Jobs.JobSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Config")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Name")
                        .IsUnique();

                    b.ToTable("job_sources", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Jobs.JobSourceLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("numeric(3,2)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JobSourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SplitAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("JobSourceId", "ExternalId")
                        .IsUnique();

                    b.ToTable("job_source_links", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("notifications", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Outreach.EmailThread", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("GmailThreadId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OutreachMessageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GmailThreadId")
                        .IsUnique();

                    b.HasIndex("OutreachMessageId")
                        .IsUnique();

                    b.ToTable("email_threads", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Outreach.FollowUp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OutreachMessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ScheduledFor")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("OutreachMessageId");

                    b.ToTable("follow_ups", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Outreach.OutreachContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ProfessorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("outreach_contacts", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Outreach.OutreachMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OutreachContactId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("OutreachContactId");

                    b.ToTable("outreach_messages", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Profile.CoverLetter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("cover_letters", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Profile.CoverLetterVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoverLetterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GeneratedForApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("StorageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CoverLetterId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("cover_letter_versions", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Profile.Education", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("education", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Profile.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("experiences", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Profile.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Headline")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.PrimitiveCollection<List<string>>("TargetRoles")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("AuthUserId")
                        .IsUnique();

                    b.ToTable("profiles", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Profile.ProfileSkill", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.HasKey("ProfileId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("profile_skills", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Profile.Resume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetCompany")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("SourceVersionId");

                    b.ToTable("resumes", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Profile.ResumeVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LockedByApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ParsedContent")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uuid");

                    b.Property<string>("StorageUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("resume_versions", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Profile.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("skills", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Tasks.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LinkedApplicationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LinkedOutreachMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.ToTable("tasks", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Universities.Professor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProfileUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("professors", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Universities.ProfessorResearchArea", b =>
                {
                    b.Property<Guid>("ProfessorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResearchAreaId")
                        .HasColumnType("uuid");

                    b.HasKey("ProfessorId", "ResearchAreaId");

                    b.HasIndex("ResearchAreaId");

                    b.ToTable("professor_research_areas", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Universities.Program", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("programs", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Universities.ResearchArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("research_areas", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Universities.Scholarship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AmountRange")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DeadlineDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("UniversityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("scholarships", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Universities.University", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("universities", "app");
                });

            modelBuilder.Entity("WorkPilot.Infrastructure.Modules.Profile.StoredResumeFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("resume_files", "app");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Agent.AgentStep", b =>
                {
                    b.HasOne("WorkPilot.Domain.Modules.Agent.AgentRun", null)
                        .WithMany("Steps")
                        .HasForeignKey("AgentRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Agent.ToolCall", b =>
                {
                    b.HasOne("WorkPilot.Domain.Modules.Agent.AgentStep", null)
                        .WithMany("ToolCalls")
                        .HasForeignKey("AgentStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Applications.ApplicationAnswer", b =>
                {
                    b.HasOne("WorkPilot.Domain.Modules.Applications.JobApplication", null)
                        .WithMany("Answers")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Applications.ApplicationEvent", b =>
                {
                    b.HasOne("WorkPilot.Domain.Modules.Applications.JobApplication", null)
                        .WithMany("Events")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Jobs.Job", b =>
                {
                    b.OwnsOne("WorkPilot.Domain.Common.Provenance", "Provenance", b1 =>
                        {
                            b1.Property<Guid>("JobId")
                                .HasColumnType("uuid");

                            b1.Property<decimal?>("Confidence")
                                .HasColumnType("numeric(5,4)");

                            b1.Property<DateTimeOffset>("RetrievedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("SourceUrl")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTimeOffset?>("VerifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("JobId");

                            b1.ToTable("jobs", "app");

                            b1.WithOwner()
                                .HasForeignKey("JobId");
                        });

                    b.Navigation("Provenance")
                        .IsRequired();
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Jobs.JobSnapshot", b =>
                {
                    b.HasOne("WorkPilot.Domain.Modules.Jobs.Job", null)
                        .WithMany("Snapshots")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkPilot.Domain.Modules.Jobs.JobSource", null)
                        .WithMany()
                        .HasForeignKey("JobSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("WorkPilot.Domain.Common.Provenance", "Provenance", b1 =>
                        {
                            b1.Property<Guid>("JobSnapshotId")
                                .HasColumnType("uuid");

                            b1.Property<decimal?>("Confidence")
                                .HasColumnType("numeric(5,4)");

                            b1.Property<DateTimeOffset>("RetrievedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("SourceUrl")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTimeOffset?>("VerifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("JobSnapshotId");

                            b1.ToTable("job_snapshots", "app");

                            b1.WithOwner()
                                .HasForeignKey("JobSnapshotId");
                        });

                    b.Navigation("Provenance")
                        .IsRequired();
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Jobs.JobSourceLink", b =>
                {
                    b.HasOne("WorkPilot.Domain.Modules.Jobs.Job", null)
                        .WithMany("Links")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkPilot.Domain.Modules.Jobs.JobSource", null)
                        .WithMany()
                        .HasForeignKey("JobSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Outreach.EmailThread", b =>
                {
                    b.HasOne("WorkPilot.Domain.Modules.Outreach.OutreachMessage", null)
                        .WithOne("Thread")
                        .HasForeignKey("WorkPilot.Domain.Modules.Outreach.EmailThread", "OutreachMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Outreach.FollowUp", b =>
                {
                    b.HasOne("WorkPilot.Domain.Modules.Outreach.OutreachMessage", null)
                        .WithMany("FollowUps")
                        .HasForeignKey("OutreachMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Outreach.OutreachMessage", b =>
                {
                    b.HasOne("WorkPilot.Domain.Modules.Outreach.OutreachContact", null)
                        .WithMany("Messages")
                        .HasForeignKey("OutreachContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Profile.CoverLetterVersion", b =>
                {
                    b.HasOne("WorkPilot.Domain.Modules.Profile.CoverLetter", null)
                        .WithMany("Versions")
                        .HasForeignKey("CoverLetterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Profile.Education", b =>
                {
                    b.HasOne("WorkPilot.Domain.Modules.Profile.Profile", null)
                        .WithMany("Education")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Profile.Experience", b =>
                {
                    b.HasOne("WorkPilot.Domain.Modules.Profile.Profile", null)
                        .WithMany("Experiences")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Profile.ProfileSkill", b =>
                {
                    b.HasOne("WorkPilot.Domain.Modules.Profile.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkPilot.Domain.Modules.Profile.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Profile.Resume", b =>
                {
                    b.HasOne("WorkPilot.Domain.Modules.Profile.ResumeVersion", null)
                        .WithMany()
                        .HasForeignKey("SourceVersionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Profile.ResumeVersion", b =>
                {
                    b.HasOne("WorkPilot.Domain.Modules.Profile.Resume", null)
                        .WithMany("Versions")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Universities.Professor", b =>
                {
                    b.HasOne("WorkPilot.Domain.Modules.Universities.University", null)
                        .WithMany("Professors")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("WorkPilot.Domain.Common.Provenance", "Provenance", b1 =>
                        {
                            b1.Property<Guid>("ProfessorId")
                                .HasColumnType("uuid");

                            b1.Property<decimal?>("Confidence")
                                .HasColumnType("numeric(5,4)");

                            b1.Property<DateTimeOffset>("RetrievedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("SourceUrl")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTimeOffset?>("VerifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("ProfessorId");

                            b1.ToTable("professors", "app");

                            b1.WithOwner()
                                .HasForeignKey("ProfessorId");
                        });

                    b.Navigation("Provenance")
                        .IsRequired();
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Universities.ProfessorResearchArea", b =>
                {
                    b.HasOne("WorkPilot.Domain.Modules.Universities.Professor", null)
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkPilot.Domain.Modules.Universities.ResearchArea", null)
                        .WithMany()
                        .HasForeignKey("ResearchAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Universities.Program", b =>
                {
                    b.HasOne("WorkPilot.Domain.Modules.Universities.University", null)
                        .WithMany("Programs")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("WorkPilot.Domain.Common.Provenance", "Provenance", b1 =>
                        {
                            b1.Property<Guid>("ProgramId")
                                .HasColumnType("uuid");

                            b1.Property<decimal?>("Confidence")
                                .HasColumnType("numeric(5,4)");

                            b1.Property<DateTimeOffset>("RetrievedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("SourceUrl")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTimeOffset?>("VerifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("ProgramId");

                            b1.ToTable("programs", "app");

                            b1.WithOwner()
                                .HasForeignKey("ProgramId");
                        });

                    b.Navigation("Provenance")
                        .IsRequired();
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Universities.Scholarship", b =>
                {
                    b.HasOne("WorkPilot.Domain.Modules.Universities.University", null)
                        .WithMany("Scholarships")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("WorkPilot.Domain.Common.Provenance", "Provenance", b1 =>
                        {
                            b1.Property<Guid>("ScholarshipId")
                                .HasColumnType("uuid");

                            b1.Property<decimal?>("Confidence")
                                .HasColumnType("numeric(5,4)");

                            b1.Property<DateTimeOffset>("RetrievedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("SourceUrl")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTimeOffset?>("VerifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("ScholarshipId");

                            b1.ToTable("scholarships", "app");

                            b1.WithOwner()
                                .HasForeignKey("ScholarshipId");
                        });

                    b.Navigation("Provenance")
                        .IsRequired();
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Universities.University", b =>
                {
                    b.OwnsOne("WorkPilot.Domain.Common.Provenance", "Provenance", b1 =>
                        {
                            b1.Property<Guid>("UniversityId")
                                .HasColumnType("uuid");

                            b1.Property<decimal?>("Confidence")
                                .HasColumnType("numeric(5,4)");

                            b1.Property<DateTimeOffset>("RetrievedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("SourceUrl")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTimeOffset?>("VerifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("UniversityId");

                            b1.ToTable("universities", "app");

                            b1.WithOwner()
                                .HasForeignKey("UniversityId");
                        });

                    b.Navigation("Provenance")
                        .IsRequired();
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Agent.AgentRun", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Agent.AgentStep", b =>
                {
                    b.Navigation("ToolCalls");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Applications.JobApplication", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Jobs.Job", b =>
                {
                    b.Navigation("Links");

                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Outreach.OutreachContact", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Outreach.OutreachMessage", b =>
                {
                    b.Navigation("FollowUps");

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Profile.CoverLetter", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Profile.Profile", b =>
                {
                    b.Navigation("Education");

                    b.Navigation("Experiences");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Profile.Resume", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("WorkPilot.Domain.Modules.Universities.University", b =>
                {
                    b.Navigation("Professors");

                    b.Navigation("Programs");

                    b.Navigation("Scholarships");
                });
#pragma warning restore 612, 618
        }
    }
}
