namespace WorkPilot.Domain.Common;

/// <summary>
/// Static ISO code tables (spec 0019): ISO 3166 alpha 2 countries with their English names, and the
/// ISO 4217 currencies in use today. Used to validate the match profile and to read a country out of a
/// job's location text. Generated once from CLDR; a new country or currency is a one line edit.
/// </summary>
public static class IsoCodes
{
    /// <summary>ISO 3166 alpha 2 code to English name.</summary>
    public static readonly IReadOnlyDictionary<string, string> Countries = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["AD"] = "Andorra",
        ["AE"] = "United Arab Emirates",
        ["AF"] = "Afghanistan",
        ["AG"] = "Antigua & Barbuda",
        ["AI"] = "Anguilla",
        ["AL"] = "Albania",
        ["AM"] = "Armenia",
        ["AO"] = "Angola",
        ["AQ"] = "Antarctica",
        ["AR"] = "Argentina",
        ["AS"] = "American Samoa",
        ["AT"] = "Austria",
        ["AU"] = "Australia",
        ["AW"] = "Aruba",
        ["AX"] = "Åland Islands",
        ["AZ"] = "Azerbaijan",
        ["BA"] = "Bosnia & Herzegovina",
        ["BB"] = "Barbados",
        ["BD"] = "Bangladesh",
        ["BE"] = "Belgium",
        ["BF"] = "Burkina Faso",
        ["BG"] = "Bulgaria",
        ["BH"] = "Bahrain",
        ["BI"] = "Burundi",
        ["BJ"] = "Benin",
        ["BL"] = "St. Barthélemy",
        ["BM"] = "Bermuda",
        ["BN"] = "Brunei",
        ["BO"] = "Bolivia",
        ["BQ"] = "Caribbean Netherlands",
        ["BR"] = "Brazil",
        ["BS"] = "Bahamas",
        ["BT"] = "Bhutan",
        ["BV"] = "Bouvet Island",
        ["BW"] = "Botswana",
        ["BY"] = "Belarus",
        ["BZ"] = "Belize",
        ["CA"] = "Canada",
        ["CC"] = "Cocos (Keeling) Islands",
        ["CD"] = "Congo - Kinshasa",
        ["CF"] = "Central African Republic",
        ["CG"] = "Congo - Brazzaville",
        ["CH"] = "Switzerland",
        ["CI"] = "Côte d’Ivoire",
        ["CK"] = "Cook Islands",
        ["CL"] = "Chile",
        ["CM"] = "Cameroon",
        ["CN"] = "China",
        ["CO"] = "Colombia",
        ["CR"] = "Costa Rica",
        ["CU"] = "Cuba",
        ["CV"] = "Cape Verde",
        ["CW"] = "Curaçao",
        ["CX"] = "Christmas Island",
        ["CY"] = "Cyprus",
        ["CZ"] = "Czechia",
        ["DE"] = "Germany",
        ["DJ"] = "Djibouti",
        ["DK"] = "Denmark",
        ["DM"] = "Dominica",
        ["DO"] = "Dominican Republic",
        ["DZ"] = "Algeria",
        ["EC"] = "Ecuador",
        ["EE"] = "Estonia",
        ["EG"] = "Egypt",
        ["EH"] = "Western Sahara",
        ["ER"] = "Eritrea",
        ["ES"] = "Spain",
        ["ET"] = "Ethiopia",
        ["FI"] = "Finland",
        ["FJ"] = "Fiji",
        ["FK"] = "Falkland Islands",
        ["FM"] = "Micronesia",
        ["FO"] = "Faroe Islands",
        ["FR"] = "France",
        ["GA"] = "Gabon",
        ["GB"] = "United Kingdom",
        ["GD"] = "Grenada",
        ["GE"] = "Georgia",
        ["GF"] = "French Guiana",
        ["GG"] = "Guernsey",
        ["GH"] = "Ghana",
        ["GI"] = "Gibraltar",
        ["GL"] = "Greenland",
        ["GM"] = "Gambia",
        ["GN"] = "Guinea",
        ["GP"] = "Guadeloupe",
        ["GQ"] = "Equatorial Guinea",
        ["GR"] = "Greece",
        ["GS"] = "South Georgia & South Sandwich Islands",
        ["GT"] = "Guatemala",
        ["GU"] = "Guam",
        ["GW"] = "Guinea-Bissau",
        ["GY"] = "Guyana",
        ["HK"] = "Hong Kong SAR China",
        ["HM"] = "Heard & McDonald Islands",
        ["HN"] = "Honduras",
        ["HR"] = "Croatia",
        ["HT"] = "Haiti",
        ["HU"] = "Hungary",
        ["ID"] = "Indonesia",
        ["IE"] = "Ireland",
        ["IL"] = "Israel",
        ["IM"] = "Isle of Man",
        ["IN"] = "India",
        ["IO"] = "British Indian Ocean Territory",
        ["IQ"] = "Iraq",
        ["IR"] = "Iran",
        ["IS"] = "Iceland",
        ["IT"] = "Italy",
        ["JE"] = "Jersey",
        ["JM"] = "Jamaica",
        ["JO"] = "Jordan",
        ["JP"] = "Japan",
        ["KE"] = "Kenya",
        ["KG"] = "Kyrgyzstan",
        ["KH"] = "Cambodia",
        ["KI"] = "Kiribati",
        ["KM"] = "Comoros",
        ["KN"] = "St. Kitts & Nevis",
        ["KP"] = "North Korea",
        ["KR"] = "South Korea",
        ["KW"] = "Kuwait",
        ["KY"] = "Cayman Islands",
        ["KZ"] = "Kazakhstan",
        ["LA"] = "Laos",
        ["LB"] = "Lebanon",
        ["LC"] = "St. Lucia",
        ["LI"] = "Liechtenstein",
        ["LK"] = "Sri Lanka",
        ["LR"] = "Liberia",
        ["LS"] = "Lesotho",
        ["LT"] = "Lithuania",
        ["LU"] = "Luxembourg",
        ["LV"] = "Latvia",
        ["LY"] = "Libya",
        ["MA"] = "Morocco",
        ["MC"] = "Monaco",
        ["MD"] = "Moldova",
        ["ME"] = "Montenegro",
        ["MF"] = "St. Martin",
        ["MG"] = "Madagascar",
        ["MH"] = "Marshall Islands",
        ["MK"] = "North Macedonia",
        ["ML"] = "Mali",
        ["MM"] = "Myanmar (Burma)",
        ["MN"] = "Mongolia",
        ["MO"] = "Macao SAR China",
        ["MP"] = "Northern Mariana Islands",
        ["MQ"] = "Martinique",
        ["MR"] = "Mauritania",
        ["MS"] = "Montserrat",
        ["MT"] = "Malta",
        ["MU"] = "Mauritius",
        ["MV"] = "Maldives",
        ["MW"] = "Malawi",
        ["MX"] = "Mexico",
        ["MY"] = "Malaysia",
        ["MZ"] = "Mozambique",
        ["NA"] = "Namibia",
        ["NC"] = "New Caledonia",
        ["NE"] = "Niger",
        ["NF"] = "Norfolk Island",
        ["NG"] = "Nigeria",
        ["NI"] = "Nicaragua",
        ["NL"] = "Netherlands",
        ["NO"] = "Norway",
        ["NP"] = "Nepal",
        ["NR"] = "Nauru",
        ["NU"] = "Niue",
        ["NZ"] = "New Zealand",
        ["OM"] = "Oman",
        ["PA"] = "Panama",
        ["PE"] = "Peru",
        ["PF"] = "French Polynesia",
        ["PG"] = "Papua New Guinea",
        ["PH"] = "Philippines",
        ["PK"] = "Pakistan",
        ["PL"] = "Poland",
        ["PM"] = "St. Pierre & Miquelon",
        ["PN"] = "Pitcairn Islands",
        ["PR"] = "Puerto Rico",
        ["PS"] = "Palestinian Territories",
        ["PT"] = "Portugal",
        ["PW"] = "Palau",
        ["PY"] = "Paraguay",
        ["QA"] = "Qatar",
        ["RE"] = "Réunion",
        ["RO"] = "Romania",
        ["RS"] = "Serbia",
        ["RU"] = "Russia",
        ["RW"] = "Rwanda",
        ["SA"] = "Saudi Arabia",
        ["SB"] = "Solomon Islands",
        ["SC"] = "Seychelles",
        ["SD"] = "Sudan",
        ["SE"] = "Sweden",
        ["SG"] = "Singapore",
        ["SH"] = "St. Helena",
        ["SI"] = "Slovenia",
        ["SJ"] = "Svalbard & Jan Mayen",
        ["SK"] = "Slovakia",
        ["SL"] = "Sierra Leone",
        ["SM"] = "San Marino",
        ["SN"] = "Senegal",
        ["SO"] = "Somalia",
        ["SR"] = "Suriname",
        ["SS"] = "South Sudan",
        ["ST"] = "São Tomé & Príncipe",
        ["SV"] = "El Salvador",
        ["SX"] = "Sint Maarten",
        ["SY"] = "Syria",
        ["SZ"] = "Eswatini",
        ["TC"] = "Turks & Caicos Islands",
        ["TD"] = "Chad",
        ["TF"] = "French Southern Territories",
        ["TG"] = "Togo",
        ["TH"] = "Thailand",
        ["TJ"] = "Tajikistan",
        ["TK"] = "Tokelau",
        ["TL"] = "Timor-Leste",
        ["TM"] = "Turkmenistan",
        ["TN"] = "Tunisia",
        ["TO"] = "Tonga",
        ["TR"] = "Turkey",
        ["TT"] = "Trinidad & Tobago",
        ["TV"] = "Tuvalu",
        ["TW"] = "Taiwan",
        ["TZ"] = "Tanzania",
        ["UA"] = "Ukraine",
        ["UG"] = "Uganda",
        ["UM"] = "U.S. Outlying Islands",
        ["US"] = "United States",
        ["UY"] = "Uruguay",
        ["UZ"] = "Uzbekistan",
        ["VA"] = "Vatican City",
        ["VC"] = "St. Vincent & Grenadines",
        ["VE"] = "Venezuela",
        ["VG"] = "British Virgin Islands",
        ["VI"] = "U.S. Virgin Islands",
        ["VN"] = "Vietnam",
        ["VU"] = "Vanuatu",
        ["WF"] = "Wallis & Futuna",
        ["WS"] = "Samoa",
        ["YE"] = "Yemen",
        ["YT"] = "Mayotte",
        ["ZA"] = "South Africa",
        ["ZM"] = "Zambia",
        ["ZW"] = "Zimbabwe",
    };

    /// <summary>ISO 4217 codes of the currencies in use today.</summary>
    public static readonly IReadOnlySet<string> Currencies = new HashSet<string>(StringComparer.Ordinal)
    {
        "AED",
        "AFN",
        "ALL",
        "AMD",
        "ANG",
        "AOA",
        "ARS",
        "AUD",
        "AWG",
        "AZN",
        "BAM",
        "BBD",
        "BDT",
        "BGN",
        "BHD",
        "BIF",
        "BMD",
        "BND",
        "BOB",
        "BRL",
        "BSD",
        "BTN",
        "BWP",
        "BYN",
        "BZD",
        "CAD",
        "CDF",
        "CHF",
        "CLP",
        "CNY",
        "COP",
        "CRC",
        "CUC",
        "CUP",
        "CVE",
        "CZK",
        "DJF",
        "DKK",
        "DOP",
        "DZD",
        "EGP",
        "ERN",
        "ETB",
        "EUR",
        "FJD",
        "FKP",
        "GBP",
        "GEL",
        "GHS",
        "GIP",
        "GMD",
        "GNF",
        "GTQ",
        "GYD",
        "HKD",
        "HNL",
        "HRK",
        "HTG",
        "HUF",
        "IDR",
        "ILS",
        "INR",
        "IQD",
        "IRR",
        "ISK",
        "JMD",
        "JOD",
        "JPY",
        "KES",
        "KGS",
        "KHR",
        "KMF",
        "KPW",
        "KRW",
        "KWD",
        "KYD",
        "KZT",
        "LAK",
        "LBP",
        "LKR",
        "LRD",
        "LSL",
        "LYD",
        "MAD",
        "MDL",
        "MGA",
        "MKD",
        "MMK",
        "MNT",
        "MOP",
        "MRU",
        "MUR",
        "MVR",
        "MWK",
        "MXN",
        "MYR",
        "MZN",
        "NAD",
        "NGN",
        "NIO",
        "NOK",
        "NPR",
        "NZD",
        "OMR",
        "PAB",
        "PEN",
        "PGK",
        "PHP",
        "PKR",
        "PLN",
        "PYG",
        "QAR",
        "RON",
        "RSD",
        "RUB",
        "RWF",
        "SAR",
        "SBD",
        "SCR",
        "SDG",
        "SEK",
        "SGD",
        "SHP",
        "SLL",
        "SOS",
        "SRD",
        "SSP",
        "STN",
        "SYP",
        "SZL",
        "THB",
        "TJS",
        "TMT",
        "TND",
        "TOP",
        "TRY",
        "TTD",
        "TWD",
        "TZS",
        "UAH",
        "UGX",
        "USD",
        "UYU",
        "UZS",
        "VES",
        "VND",
        "VUV",
        "WST",
        "XAF",
        "XCD",
        "XOF",
        "XPF",
        "YER",
        "ZAR",
        "ZMW",
    };

    // Other common ways a posting names a country, besides its ISO name and code.
    private static readonly Dictionary<string, string> CountryAliases = new(StringComparer.Ordinal)
    {
        ["usa"] = "US",
        ["united states of america"] = "US",
        ["u.s."] = "US",
        ["u.s.a."] = "US",
        ["uk"] = "GB",
        ["england"] = "GB",
        ["scotland"] = "GB",
        ["wales"] = "GB",
        ["great britain"] = "GB",
        ["uae"] = "AE",
        ["the netherlands"] = "NL",
        ["holland"] = "NL",
        ["south korea"] = "KR",
        ["korea"] = "KR",
        ["czech republic"] = "CZ",
        ["russia"] = "RU",
        ["turkey"] = "TR",
        ["vietnam"] = "VN",
    };

    private static readonly Dictionary<string, string> CountryByName = BuildCountryNames();

    /// <summary>True when <paramref name="code"/> is a known ISO 3166 alpha 2 code (upper case).</summary>
    public static bool IsCountry(string? code) => code is not null && Countries.ContainsKey(code);

    /// <summary>True when <paramref name="code"/> is a known ISO 4217 code (upper case).</summary>
    public static bool IsCurrency(string? code) => code is not null && Currencies.Contains(code);

    /// <summary>
    /// The ISO code for a country written as a name (<c>Germany</c>, <c>United States</c>, <c>UK</c>)
    /// or as an alpha 2 code (<c>DE</c>), case insensitive; null when not recognized.
    /// </summary>
    public static string? FindCountry(string? text)
    {
        if (string.IsNullOrWhiteSpace(text))
        {
            return null;
        }

        var trimmed = text.Trim();
        if (trimmed.Length == 2 && Countries.ContainsKey(trimmed.ToUpperInvariant()))
        {
            return trimmed.ToUpperInvariant();
        }

        return CountryByName.GetValueOrDefault(trimmed.ToLowerInvariant());
    }

    private static Dictionary<string, string> BuildCountryNames()
    {
        var names = new Dictionary<string, string>(CountryAliases, StringComparer.Ordinal);
        foreach (var (code, name) in Countries)
        {
            names.TryAdd(name.ToLowerInvariant(), code);
        }

        return names;
    }
}
